name: PR Notify
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send notification
        uses: rccyx/notify@main
        with:
          token: ${{ secrets.RCCYX_NOTIFY_TOKEN }}
          # type: SERVICE   # optional; defaults to SERVICE
          title: ${{ github.event.pull_request.title }}
          message: >-
            PR #${{ github.event.number }} by ${{ github.actor }}
            on ${{ github.repository }}
            (${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }})
            ${{ github.event.pull_request.html_url }}

